### ISSUE TITLE
Terms & conditions and Privacy pages.

### ISSUE THREAD

**Issue by bookmebus** [bookmebus/vshop168#109]
@sirivudh get the content

**Comment by sirivudh** [comment]
Title: **Privacy Policy**
url: https://vtenh.com/privacy-policy
Title: **Terms and Conditions**
url: https://vtenh.com/term-and-conditions
Title: **Return Policy**
url: https://vtenh.com/return-policy
Title: **Cookies Policy**
url: https://vtenh.com/cookies-policy

Please find the policies here:
https://drive.google.com/drive/folders/1JKgHQaj2QEw_gy4X3Qxbre7r0MWTP44Z?usp=sharing
