### ISSUE TITLE
Update main nav bar

### ISSUE THREAD

**Issue by bookmebus** [bookmebus/vshop168#125]

**Comment by bookmebus** [comment]
![vtenh main nav bar](https://user-images.githubusercontent.com/38972772/102171061-41028e80-3ec8-11eb-9ef0-054fd331a37d.png)

**Comment by bookmebus** [comment]
Follow spree design https://demo.spreecommerce.org/

**Comment by MenghourLao** [comment]
Here is link for Nav Bar updated!

https://xd.adobe.com/view/da45048e-ce76-42d8-8b18-e48f444a9fb3-8f16/
