### ISSUE TITLE
Vmall Brand main menu content

### ISSUE THREAD

**Issue by channainfo** [bookmebus/vshop168#232]

**Comment by sirivudh** [comment]
@channainfo Please find the design for VMALL page in the link below.

Please note a few changes: 
1. Change page name from VMALL Brands to All Brands
2. Setup Suggestion: 
- Featured Brands = Taxon -> Featured Brands (is trending)
- All Brands = Taxon -> Featured Brands


https://xd.adobe.com/view/4d101ef1-8b87-47a9-bb8f-0d7ef21d7242-1843/screen/8e4863a3-fb64-496a-aa25-b4b33549292b/
