### ISSUE TITLE
Add "Become a Seller" on menu homepage

### ISSUE THREAD

**Issue by MenghourLao** [bookmebus/vshop168#237]
**Check link below**

https://xd.adobe.com/view/da45048e-ce76-42d8-8b18-e48f444a9fb3-8f16/

**Comment by sirivudh** [comment]
Please find the embed code here;

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSePeu1V9zaByX6LYUC6tSPHw8n-ly7GAoFEWgqucZhDrhq0zA/viewform?embedded=true" width="640" height="2040" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

**Comment by sirivudh** [comment]
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSePeu1V9zaByX6LYUC6tSPHw8n-ly7GAoFEWgqucZhDrhq0zA/viewform?embedded=true" width="640" height="2040" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

**Comment by channainfo** [comment]
@sirivudh noted.
