### ISSUE TITLE
Filter chain halted as :ensure_order rendered or redirected Completed 401 Unauthorized 

### ISSUE THREAD

**Issue by bookmebus** [bookmebus/vshop168#95]
When checking out ( product details page ) some time cause: 
```
Filter chain halted as :ensure_order rendered or redirected Completed 401 Unauthorized 
```
Error.

**Comment by bookmebus** [comment]
I've just tried Doorkeeper::AccessToken.destroy_all then it works.

**Comment by channainfo** [comment]
I've just tried Doorkeeper::AccessToken.destroy_all then it works. Need to test more what causes this to fail ( token expired, ... )
